### ISSUE TITLE
Add a map editing component

### ISSUE THREAD

**Issue by bhou** [ananas-analytics/ananas-desktop#87]
This componnet will be used in the steps, which has map type config field.

```yaml
config:
    mapTypeField:
        key1: value1
        key2: value2
        ...
```

Both key and value are string type
